.\" Copyright (C) 2009 Sony Computer Entertainment Inc.
.\" Copyright 2009 Sony Corp.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; version 2 of the License.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.Dd ""
.Dt pb-event 8
.Os
.\"
.Sh NAME
.\" ====
.Nm pb-event
.Nd Event helper for the Petitboot bootloader
.\"
.Sh SYNOPSIS
.\" ========
.Nm
.\"
.Sh DESCRIPTION
.\" ===========
The pb-event utility is used to send user mode events to pb-discover, the
petitboot device discovery daemon.
.\"
.Sh SEE ALSO
.\" ========
.Xr petitboot 8 , Xr petitboot-nc 8 , Xr petitboot-twin 8 , Xr pb-discover 8
.\"
.Sh REPORTING BUGS
.\" ==============
Send bug reports to Geoff Levand <geoff @ infradead.org>
