.\" Copyright Geoff Levand <geoff@infradead.org>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; version 2 of the License.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.Dd ""
.Dt pb-udhcpc 8
.Os
.\"
.Sh NAME
.\" ====
.Nm pb-udhcpc
.Nd Petitboot udhcpc user script
.\"
.Sh DESCRIPTION
.\" ===========
Petitboot udhcpc user script.  Should be run by udhcpc when
there is a change in the dhcp configuration.  For more info
see the udhcpc man page and the Linux kernel source file
Documentation/filesystems/nfsroot.txt.
.\"
.Sh SEE ALSO
.\" ========
.Xr petitboot 8 , Xr petitboot-nc 8 , Xr petitboot-twin 8 , Xr pb-discover 8 , Xr pb-event 8
.\"
.Sh REPORTING BUGS
.\" ==============
Send bug reports to Geoff Levand <geoff @ infradead.org>
