#!/bin/sh

# Hook to set the linux,stdout-path property from an nvram property
# (named $nvram_prop).

nvram_prop=petitboot,console

# we need to be using a dtb
[ -n "$boot_dtb" ] || exit

console=$(nvram --print-config="$nvram_prop")

[ $? = 0 -a -n "$console" ] || exit

dtb_in=$boot_dtb
dtb_out=$(mktemp)

(
	dtc -I dtb -O dts $dtb_in
	echo '/ { chosen { linux,stdout-path = "'$console'"; }; }; '
) | dtc -I dts -O dtb -o $dtb_out

[ $? = 0 ] && mv $dtb_out $dtb_in
